version: '3'

services:
  postgresql:
    image: postgres
    container_name: apples
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DATABASE=lesson
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-apples
    ports:
      - '6379-6379'
